name: RAG
run-name: ${{ github.actor }} ML HUB ${{ github.ref }} ${{ github.sha }}
on:
  push:
    paths:
      - 'projects/rag/**'
      - .github/workflows/rag.yml
      - .github/docker/rag.Dockerfile
      - libs/**
    branches:
      - main
      - dev

env:
  PROJECT_ID: story-chief-161712
  GAR_LOCATION: europe-west1
  SERVICE: ai-platform
  REGION: europe-west1

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GSC_BACKEND_SERVICE_ACC}}'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          username: '_json_key'
          password: '${{ secrets.GCP_SERVICE }}'
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'

      - name: Build & Push and ingest secrets API
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: '${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/rag:${{ github.sha }}'
          file: .github/docker/rag.Dockerfile
          build-args: |
            GCP_SERVICE_ACCOUNT=${{ secrets.GSC_BACKEND_SERVICE_ACC }}
            COHERE_API_KEY=${{ secrets.COHERE_API_KEY }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}

      - name: Deploy to Cloud Run
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: rag
          region: ${{ env.REGION }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/rag:${{ github.sha }}
          tag: ${{ github.ref == 'refs/heads/dev' && 'dev' || null }}
          no_traffic: ${{ github.ref == 'refs/heads/dev' && true || false }}
          secrets: |
            GCP_SERVICE_ACCOUNT=GSC_BACKEND_SERVICE_ACC:latest
            COHERE_API_KEY=COHERE_API_KEY:latest
            OPENAI_API_KEY=OPENAI_API_KEY:latest
          env_vars: |
            ENVIRONMENT=${{ github.ref == 'refs/heads/dev' && 'dev' || 'production' }}
            GCP_LOCATION_ID=europe-west1
            GCP_PROJECT_ID=${{ env.PROJECT_ID }}
            API_VERSION=v1